### ISSUE TITLE
Expected [K, V] tuple: T

### ISSUE THREAD

**Issue by sunqingyao** [looch/gitbook-plugin-translated#1]
I've installed this plugin and tried to configure it. Then I got the error `Expected [K, V] tuple: T`

Using Gitbook Editor for OS X, version 6.0.0

**Comment by looch** [comment]
I do not know what it is, but I have a new version, and contains detailed instructions, you can try it.

我不知道那是什么，但我有一个新的版本，并包含详细说明，你可以试试看它。

file `book.json`:

```json
  "plugins": [
    "translated@0.1.0"
  ]
```

run `gitbook install`

**--- from google translate**
